#!/usr/bin/env bash

# Robust cpptraj analysis for 3 MD replicates
# Author: Lucas/ChatGPT revised version with H-bond lifetime analysis
#
# Main outputs per replicate:
#   replicate_analysis_1/
#   replicate_analysis_2/
#   replicate_analysis_3/
#
# Expected input trajectories, by priority:
#   step5_production_1.nc, step5_production_2.nc, step5_production_3.nc
#   step5_production.1.nc, step5_production.2.nc, step5_production.3.nc
#   step5_1.nc, step5_2.nc, step5_3.nc
#   For replicate 1 only, also accepts: step5_production.nc
#
# This script does NOT abort the entire loop if one analysis fails,
# unless CONTINUE_ON_ERROR=no.
#
# Main analyses:
#   01) trajectory centering / imaging
#   02) protein C-alpha RMSD and ligand RMSD
#   03) protein C-alpha RMSF
#   04) protein radius of gyration
#   05) protein-ligand H-bonds + avgout + series + lifetime
#   06) ligand clustering based on ligand RMSD
#
# H-bond outputs per replicate:
#   hbond_lig_prot.dat
#       Total number of protein-ligand H-bonds per frame.
#
#   hbond_lig_prot_avg.dat
#       Average/population of each protein-ligand H-bond.
#
#   hbond_lig_prot_series.gnu
#       Raw 0/1 time series for each detected H-bond.
#
#   hbond_lig_prot_lifetime.dat
#       Lifetime statistics for all protein-ligand H-bonds.
#
#   crv.hbond_lig_prot_lifetime.dat
#       Lifetime curves generated by cpptraj.
#
# Directional H-bond outputs:
#   hb_ligD_protA.dat
#   hb_ligD_protA_avg.dat
#   hb_ligD_protA_series.gnu
#   hb_ligD_protA_lifetime.dat
#
#   hb_protD_ligA.dat
#   hb_protD_ligA_avg.dat
#   hb_protD_ligA_series.gnu
#   hb_protD_ligA_lifetime.dat
#
#   hbond_lig_prot_directions.dat
#   hbond_lig_prot_from_directions.dat

set -uo pipefail

# =========================================================
# CONFIGURATION
# =========================================================

# Topology file
PARM="${PARM:-step3_input.parm7}"

# Last protein residue
# For your current system, this was set as 623.
PROT_LAST_RES="${PROT_LAST_RES:-623}"

# Masks
PROT_MASK=":1-${PROT_LAST_RES}"
CA_MASK="${PROT_MASK}@CA"
LIG_MASK="${LIG_MASK:-:1CU,0CU}"

# Number of ligand clusters
NCLUSTERS="${NCLUSTERS:-3}"

# Reduces clustering cost: uses 1 frame every N frames
CLUSTER_SIEVE="${CLUSTER_SIEVE:-10}"

# H-bond geometric criteria
# In cpptraj, the keyword is "dist", not "distance".
HBOND_DIST="${HBOND_DIST:-3.5}"
HBOND_ANGLE="${HBOND_ANGLE:-120}"

# Lifetime options
# Default: whole trajectory, data considered present when > 0.5.
HBOND_LIFETIME_CUT="${HBOND_LIFETIME_CUT:-0.5}"

# Optional smoothing:
# 0 = disabled.
# Example: HBOND_LIFETIME_FUZZ=1 ignores one-frame interruptions.
HBOND_LIFETIME_FUZZ="${HBOND_LIFETIME_FUZZ:-0}"

# Optional windowed lifetime analysis:
# empty or 0 = disabled.
# Example: HBOND_LIFETIME_WINDOW=100 calculates lifetime in windows of 100 frames.
HBOND_LIFETIME_WINDOW="${HBOND_LIFETIME_WINDOW:-}"

# Replicates
REPLICATES=(${REPLICATES:-1 2 3})

# MPI/CPU settings
CPU_THREADS="${CPU_THREADS:-12}"

# USE_MPI options:
#   auto = use cpptraj.MPI for light analyses if available, otherwise serial cpptraj
#   yes  = require cpptraj.MPI + mpirun for light analyses
#   no   = use serial cpptraj for all analyses
USE_MPI="${USE_MPI:-auto}"

# Continue to next steps/replicates after errors?
# Recommended: yes
CONTINUE_ON_ERROR="${CONTINUE_ON_ERROR:-yes}"

# Overwrite previous output folders?
# yes = remove replicate_analysis_i before rerunning
# no  = keep folder and overwrite only files with same names
CLEAN_OUTPUT="${CLEAN_OUTPUT:-no}"

# Summary file
SUMMARY_FILE="${SUMMARY_FILE:-cpptraj_replicates_summary.tsv}"

# =========================================================
# BASIC CHECKS
# =========================================================

fail_global=0

if [[ ! -f "$PARM" ]]; then
    echo "ERROR: topology file not found: $PARM"
    exit 1
fi

if [[ -z "$PROT_LAST_RES" || "$PROT_LAST_RES" == "XXX" ]]; then
    echo "ERROR: set PROT_LAST_RES to the last protein residue."
    echo "Example:"
    echo "  PROT_LAST_RES=623 bash run_cpptraj_replicates_lifetime.sh"
    exit 1
fi

if ! command -v cpptraj &>/dev/null; then
    echo "ERROR: serial cpptraj was not found in PATH."
    exit 1
fi

CPPTRAJ_SERIAL_CMD=(cpptraj)
HAVE_MPI="no"

if command -v cpptraj.MPI &>/dev/null && command -v mpirun &>/dev/null; then
    HAVE_MPI="yes"
    CPPTRAJ_MPI_CMD=(mpirun -np "${CPU_THREADS}" cpptraj.MPI)
fi

case "$USE_MPI" in
    auto)
        if [[ "$HAVE_MPI" == "yes" ]]; then
            export OMP_NUM_THREADS=1
            echo "Using cpptraj.MPI with ${CPU_THREADS} MPI processes for light analyses."
            echo "Serial cpptraj will be used for H-bonds and clustering."
        else
            export OMP_NUM_THREADS="${CPU_THREADS}"
            export OMP_PROC_BIND=close
            export OMP_PLACES=cores
            echo "cpptraj.MPI/mpirun not found. Using serial cpptraj for all analyses."
        fi
        ;;
    yes)
        if [[ "$HAVE_MPI" != "yes" ]]; then
            echo "ERROR: USE_MPI=yes, but cpptraj.MPI or mpirun was not found."
            exit 1
        fi
        export OMP_NUM_THREADS=1
        echo "Using cpptraj.MPI with ${CPU_THREADS} MPI processes for light analyses."
        echo "Serial cpptraj will be used for H-bonds and clustering."
        ;;
    no)
        export OMP_NUM_THREADS="${CPU_THREADS}"
        export OMP_PROC_BIND=close
        export OMP_PLACES=cores
        echo "Using serial cpptraj for all analyses with OMP_NUM_THREADS=${CPU_THREADS}."
        ;;
    *)
        echo "ERROR: invalid USE_MPI value: $USE_MPI"
        echo "Allowed values: auto, yes, no"
        exit 1
        ;;
esac

# =========================================================
# AUXILIARY FUNCTIONS
# =========================================================

timestamp() {
    date "+%Y-%m-%d %H:%M:%S"
}

print_cmd() {
    printf "%q " "$@"
    printf "\n"
}

record_status() {
    local rep="$1"
    local step="$2"
    local status="$3"
    local log_file="$4"
    local note="$5"
    printf "%s\t%s\t%s\t%s\t%s\n" "$rep" "$step" "$status" "$log_file" "$note" >> "$SUMMARY_FILE"
}

find_trajectory() {
    local rep="$1"

    local candidates=(
        "step5_production_${rep}.nc"
        "step5_production.${rep}.nc"
        "step5_${rep}.nc"
    )

    if [[ "$rep" == "1" ]]; then
        candidates+=("step5_production.nc")
    fi

    local f
    for f in "${candidates[@]}"; do
        if [[ -f "$f" ]]; then
            echo "$f"
            return 0
        fi
    done

    return 1
}

build_lifetime_options() {
    local opts="cut ${HBOND_LIFETIME_CUT}"

    if [[ -n "$HBOND_LIFETIME_WINDOW" && "$HBOND_LIFETIME_WINDOW" != "0" ]]; then
        opts="${opts} window ${HBOND_LIFETIME_WINDOW}"
    fi

    if [[ -n "$HBOND_LIFETIME_FUZZ" && "$HBOND_LIFETIME_FUZZ" != "0" ]]; then
        opts="${opts} fuzz ${HBOND_LIFETIME_FUZZ}"
    fi

    echo "$opts"
}

prepare_lifetime_aux_dirs() {
    local outdir="$1"

    # cpptraj creates auxiliary files by prefixing the full output name:
    #   crv.<filename>
    # If <filename> contains a directory, this can become:
    #   crv.replicate_analysis_1/file.dat
    # Therefore we create these directories in advance and later collect the files.
    mkdir -p "crv.${outdir}" "avg.${outdir}" "max.${outdir}" 2>/dev/null || true
}

collect_lifetime_aux_files() {
    local outdir="$1"

    local prefix
    local base

    for prefix in crv avg max; do
        if [[ -d "${prefix}.${outdir}" ]]; then
            shopt -s nullglob
            for f in "${prefix}.${outdir}"/*; do
                base="$(basename "$f")"
                mv -f "$f" "${outdir}/${prefix}.${base}"
            done
            shopt -u nullglob
            rmdir "${prefix}.${outdir}" 2>/dev/null || true
        fi
    done
}

run_cpptraj_command() {
    local mode="$1"
    local input_file="$2"
    local traj_file="$3"
    local log_file="$4"

    local -a cmd

    if [[ "$mode" == "mpi" ]]; then
        cmd=("${CPPTRAJ_MPI_CMD[@]}")
    else
        cmd=("${CPPTRAJ_SERIAL_CMD[@]}")
    fi

    {
        echo "# Started: $(timestamp)"
        echo "# Mode: $mode"
        echo -n "# Command: "
        print_cmd "${cmd[@]}" -p "$PARM" -y "$traj_file" -i "$input_file"
        echo
    } > "$log_file"

    "${cmd[@]}" -p "$PARM" -y "$traj_file" -i "$input_file" >> "$log_file" 2>&1
    local rc=$?

    {
        echo
        echo "# Finished: $(timestamp)"
        echo "# Exit code: $rc"
    } >> "$log_file"

    return "$rc"
}

run_cpptraj_step() {
    local rep="$1"
    local step_name="$2"
    local input_file="$3"
    local traj_file="$4"
    local log_file="$5"
    local preferred_mode="$6"

    echo "  -> ${step_name}"

    # Serial-only steps
    if [[ "$preferred_mode" == "serial" ]]; then
        if run_cpptraj_command serial "$input_file" "$traj_file" "$log_file"; then
            record_status "$rep" "$step_name" "OK" "$log_file" "serial"
            return 0
        else
            record_status "$rep" "$step_name" "FAILED" "$log_file" "serial"
            echo "     ERROR: ${step_name} failed. Inspect: ${log_file}"
            return 1
        fi
    fi

    # Light analyses: MPI when available/requested, otherwise serial.
    if [[ "$USE_MPI" != "no" && "$HAVE_MPI" == "yes" ]]; then
        if run_cpptraj_command mpi "$input_file" "$traj_file" "$log_file"; then
            record_status "$rep" "$step_name" "OK" "$log_file" "mpi"
            return 0
        else
            echo "     WARNING: MPI failed for ${step_name}. Trying serial fallback..."
            local fallback_log="${log_file%.log}_serial_fallback.log"

            if run_cpptraj_command serial "$input_file" "$traj_file" "$fallback_log"; then
                record_status "$rep" "$step_name" "OK" "$fallback_log" "serial fallback after MPI failure"
                return 0
            else
                record_status "$rep" "$step_name" "FAILED" "$log_file" "MPI failed; serial fallback also failed: ${fallback_log}"
                echo "     ERROR: ${step_name} failed in MPI and serial fallback."
                echo "     Inspect: ${log_file}"
                echo "     Inspect: ${fallback_log}"
                return 1
            fi
        fi
    else
        if run_cpptraj_command serial "$input_file" "$traj_file" "$log_file"; then
            record_status "$rep" "$step_name" "OK" "$log_file" "serial"
            return 0
        else
            record_status "$rep" "$step_name" "FAILED" "$log_file" "serial"
            echo "     ERROR: ${step_name} failed. Inspect: ${log_file}"
            return 1
        fi
    fi
}

require_output_file() {
    local rep="$1"
    local step_name="$2"
    local output_file="$3"
    local log_file="$4"

    if [[ -s "$output_file" ]]; then
        return 0
    fi

    record_status "$rep" "${step_name}_output_check" "FAILED" "$log_file" "missing or empty output: ${output_file}"
    echo "     ERROR: expected output was not created or is empty: ${output_file}"
    return 1
}

warn_if_missing_output_file() {
    local rep="$1"
    local step_name="$2"
    local output_file="$3"
    local log_file="$4"

    if [[ -s "$output_file" ]]; then
        return 0
    fi

    record_status "$rep" "${step_name}_output_check" "WARNING" "$log_file" "missing or empty optional output: ${output_file}"
    echo "     WARNING: optional output was not created or is empty: ${output_file}"
    return 1
}

maybe_abort_or_continue() {
    local msg="$1"

    if [[ "$CONTINUE_ON_ERROR" == "yes" ]]; then
        echo "     Continuing because CONTINUE_ON_ERROR=yes."
        return 0
    fi

    echo "$msg"
    exit 1
}

make_directional_hbond_summary() {
    local rep="$1"
    local outdir="$2"
    local log_file="$3"

    local hb_lig_prot="${outdir}/hb_ligD_protA.dat"
    local hb_prot_lig="${outdir}/hb_protD_ligA.dat"

    local clean_lig_prot="${outdir}/hb_ligD_protA.clean.tmp"
    local clean_prot_lig="${outdir}/hb_protD_ligA.clean.tmp"

    if [[ ! -s "$hb_lig_prot" || ! -s "$hb_prot_lig" ]]; then
        record_status "$rep" "05_hbond_directional_merge" "WARNING" "$log_file" "one or both directional H-bond files are missing"
        echo "     WARNING: H-bond directional files were not created."
        return 1
    fi

    # Extract first two numeric columns: Frame and H-bond count.
    awk '
        $1 !~ /^#/ && NF >= 2 && $1 ~ /^[0-9]+$/ {
            print $1, $2
        }
    ' "$hb_lig_prot" > "$clean_lig_prot"

    awk '
        $1 !~ /^#/ && NF >= 2 && $1 ~ /^[0-9]+$/ {
            print $1, $2
        }
    ' "$hb_prot_lig" > "$clean_prot_lig"

    if [[ ! -s "$clean_lig_prot" || ! -s "$clean_prot_lig" ]]; then
        record_status "$rep" "05_hbond_directional_merge" "WARNING" "$log_file" "could not parse H-bond count columns"
        echo "     WARNING: Could not parse H-bond count columns."
        rm -f "$clean_lig_prot" "$clean_prot_lig"
        return 1
    fi

    paste "$clean_lig_prot" "$clean_prot_lig" | awk '
        BEGIN {
            print "#Frame LigD_ProtA ProtD_LigA Total"
        }
        NF >= 4 {
            print $1, $2, $4, $2 + $4
        }
    ' > "${outdir}/hbond_lig_prot_directions.dat"

    paste "$clean_lig_prot" "$clean_prot_lig" | awk '
        BEGIN {
            print "#Frame Total"
        }
        NF >= 4 {
            print $1, $2 + $4
        }
    ' > "${outdir}/hbond_lig_prot_from_directions.dat"

    rm -f "$clean_lig_prot" "$clean_prot_lig"

    if [[ -s "${outdir}/hbond_lig_prot_directions.dat" ]]; then
        record_status "$rep" "05_hbond_directional_merge" "OK" "$log_file" "created directional H-bond summary"
        return 0
    fi

    record_status "$rep" "05_hbond_directional_merge" "WARNING" "$log_file" "final directional H-bond output is empty"
    return 1
}

# =========================================================
# INITIALIZE SUMMARY
# =========================================================

printf "Replicate\tStep\tStatus\tLog\tNote\n" > "$SUMMARY_FILE"

HBOND_LIFETIME_OPTIONS="$(build_lifetime_options)"

echo
echo "========================================================="
echo "CPPTRAJ REPLICATE ANALYSIS WITH H-BOND LIFETIME"
echo "========================================================="
echo "Topology:             $PARM"
echo "Protein mask:         $PROT_MASK"
echo "Protein CA mask:      $CA_MASK"
echo "Ligand mask:          $LIG_MASK"
echo "Replicates:           ${REPLICATES[*]}"
echo "Cluster sieve:        $CLUSTER_SIEVE"
echo "H-bond dist cutoff:   $HBOND_DIST Angstrom"
echo "H-bond angle cutoff:  $HBOND_ANGLE degrees"
echo "Lifetime options:     $HBOND_LIFETIME_OPTIONS"
echo "Summary file:         $SUMMARY_FILE"
echo "========================================================="
echo

# =========================================================
# REPLICATE LOOP
# =========================================================

for i in "${REPLICATES[@]}"; do

    echo "--------------------------------------"
    echo "Processing replicate ${i}"
    echo "--------------------------------------"

    TRAJ=""
    if TRAJ="$(find_trajectory "$i")"; then
        echo "Trajectory: ${TRAJ}"
    else
        echo "WARNING: no trajectory found for replicate ${i}."
        echo "Expected examples: step5_production_${i}.nc or step5_production.${i}.nc"
        record_status "$i" "trajectory_check" "SKIPPED" "-" "trajectory not found"
        continue
    fi

    OUTDIR="replicate_analysis_${i}"

    if [[ "$CLEAN_OUTPUT" == "yes" && -d "$OUTDIR" ]]; then
        echo "Removing previous output directory: $OUTDIR"
        rm -rf "$OUTDIR"
    fi

    mkdir -p "$OUTDIR"
    prepare_lifetime_aux_dirs "$OUTDIR"

    rep_failed=0

    # =====================================================
    # 01) Trajectory centering
    # =====================================================

    cat > "${OUTDIR}/01_centering.in" << EOF_IN
autoimage anchor ${PROT_MASK}
center ${PROT_MASK} mass origin
image origin center
rms first ${CA_MASK}
trajout ${OUTDIR}/step5_centered_${i}.nc netcdf
run
quit
EOF_IN

    if ! run_cpptraj_step "$i" "01_centering" "${OUTDIR}/01_centering.in" "$TRAJ" "${OUTDIR}/01_centering.log" "light"; then
        rep_failed=1
        maybe_abort_or_continue "Aborting after centering failure."
        echo "Skipping remaining analyses for replicate ${i}, because centered trajectory is required."
        continue
    fi

    CENTERED_TRAJ="${OUTDIR}/step5_centered_${i}.nc"

    if ! require_output_file "$i" "01_centering" "$CENTERED_TRAJ" "${OUTDIR}/01_centering.log"; then
        rep_failed=1
        maybe_abort_or_continue "Aborting because centered trajectory was not created."
        echo "Skipping remaining analyses for replicate ${i}, because centered trajectory is required."
        continue
    fi

    # =====================================================
    # 02) Ligand RMSD after fitting protein C-alpha
    # =====================================================

    cat > "${OUTDIR}/02_rmsd_ligand.in" << EOF_IN
rms Protein first ${CA_MASK} out ${OUTDIR}/rmsd_protein_ca.dat
rms Ligand first ${LIG_MASK} out ${OUTDIR}/rmsd_ligand.dat
run
quit
EOF_IN

    if run_cpptraj_step "$i" "02_rmsd_ligand" "${OUTDIR}/02_rmsd_ligand.in" "$CENTERED_TRAJ" "${OUTDIR}/02_rmsd_ligand.log" "light"; then
        require_output_file "$i" "02_rmsd_ligand" "${OUTDIR}/rmsd_ligand.dat" "${OUTDIR}/02_rmsd_ligand.log" || rep_failed=1
    else
        rep_failed=1
        maybe_abort_or_continue "Aborting after ligand RMSD failure."
    fi

    # =====================================================
    # 03) Per-residue RMSF C-alpha
    # =====================================================

    cat > "${OUTDIR}/03_rmsf_ca.in" << EOF_IN
rms first ${CA_MASK}
atomicfluct out ${OUTDIR}/rmsf_ca.dat ${CA_MASK} byres
run
quit
EOF_IN

    if run_cpptraj_step "$i" "03_rmsf_ca" "${OUTDIR}/03_rmsf_ca.in" "$CENTERED_TRAJ" "${OUTDIR}/03_rmsf_ca.log" "light"; then
        require_output_file "$i" "03_rmsf_ca" "${OUTDIR}/rmsf_ca.dat" "${OUTDIR}/03_rmsf_ca.log" || rep_failed=1
    else
        rep_failed=1
        maybe_abort_or_continue "Aborting after RMSF failure."
    fi

    # =====================================================
    # 04) Radius of gyration
    # =====================================================

    cat > "${OUTDIR}/04_radgyr.in" << EOF_IN
radgyr ${PROT_MASK} out ${OUTDIR}/rg_protein.dat
run
quit
EOF_IN

    if run_cpptraj_step "$i" "04_radgyr" "${OUTDIR}/04_radgyr.in" "$CENTERED_TRAJ" "${OUTDIR}/04_radgyr.log" "light"; then
        require_output_file "$i" "04_radgyr" "${OUTDIR}/rg_protein.dat" "${OUTDIR}/04_radgyr.log" || rep_failed=1
    else
        rep_failed=1
        maybe_abort_or_continue "Aborting after radius of gyration failure."
    fi

    # =====================================================
    # 05) Ligand-protein H-bonds + lifetime
    #
    # HBALL:
    #   all intermolecular protein-ligand H-bonds,
    #   independent of donor/acceptor direction.
    #
    # HBLIGPROT:
    #   ligand as donor, protein as acceptor.
    #
    # HBPROTLIG:
    #   protein as donor, ligand as acceptor.
    #
    # "series" is required so that cpptraj creates HB[solutehb],
    # which is used by lifetime.
    # =====================================================

    cat > "${OUTDIR}/05_hbond_lifetime.in" << EOF_IN
autoimage anchor ${PROT_MASK}

# ---------------------------------------------------------
# All protein-ligand intermolecular H-bonds
# ---------------------------------------------------------
hbond HBALL ${PROT_MASK},${LIG_MASK} \
    out ${OUTDIR}/hbond_lig_prot.dat \
    avgout ${OUTDIR}/hbond_lig_prot_avg.dat \
    series uuseries ${OUTDIR}/hbond_lig_prot_series.gnu \
    nointramol \
    image \
    dist ${HBOND_DIST} \
    angle ${HBOND_ANGLE} \
    printatomnum

# ---------------------------------------------------------
# Direction 1: ligand donor, protein acceptor
# ---------------------------------------------------------
hbond HBLIGPROT \
    out ${OUTDIR}/hb_ligD_protA.dat \
    avgout ${OUTDIR}/hb_ligD_protA_avg.dat \
    donormask ${LIG_MASK} \
    acceptormask ${PROT_MASK} \
    series uuseries ${OUTDIR}/hb_ligD_protA_series.gnu \
    image \
    dist ${HBOND_DIST} \
    angle ${HBOND_ANGLE} \
    printatomnum

# ---------------------------------------------------------
# Direction 2: protein donor, ligand acceptor
# ---------------------------------------------------------
hbond HBPROTLIG \
    out ${OUTDIR}/hb_protD_ligA.dat \
    avgout ${OUTDIR}/hb_protD_ligA_avg.dat \
    donormask ${PROT_MASK} \
    acceptormask ${LIG_MASK} \
    series uuseries ${OUTDIR}/hb_protD_ligA_series.gnu \
    image \
    dist ${HBOND_DIST} \
    angle ${HBOND_ANGLE} \
    printatomnum

run

# ---------------------------------------------------------
# Lifetime analyses
# ---------------------------------------------------------
runanalysis lifetime HBALL[solutehb] out ${OUTDIR}/hbond_lig_prot_lifetime.dat ${HBOND_LIFETIME_OPTIONS}
runanalysis lifetime HBLIGPROT[solutehb] out ${OUTDIR}/hb_ligD_protA_lifetime.dat ${HBOND_LIFETIME_OPTIONS}
runanalysis lifetime HBPROTLIG[solutehb] out ${OUTDIR}/hb_protD_ligA_lifetime.dat ${HBOND_LIFETIME_OPTIONS}

quit
EOF_IN

    if run_cpptraj_step "$i" "05_hbond_lifetime" "${OUTDIR}/05_hbond_lifetime.in" "$CENTERED_TRAJ" "${OUTDIR}/05_hbond_lifetime.log" "serial"; then

        collect_lifetime_aux_files "$OUTDIR"

        require_output_file "$i" "05_hbond_lifetime" "${OUTDIR}/hbond_lig_prot.dat" "${OUTDIR}/05_hbond_lifetime.log" || rep_failed=1
        require_output_file "$i" "05_hbond_lifetime" "${OUTDIR}/hbond_lig_prot_avg.dat" "${OUTDIR}/05_hbond_lifetime.log" || rep_failed=1
        require_output_file "$i" "05_hbond_lifetime" "${OUTDIR}/hbond_lig_prot_series.gnu" "${OUTDIR}/05_hbond_lifetime.log" || rep_failed=1
        require_output_file "$i" "05_hbond_lifetime" "${OUTDIR}/hbond_lig_prot_lifetime.dat" "${OUTDIR}/05_hbond_lifetime.log" || rep_failed=1

        warn_if_missing_output_file "$i" "05_hbond_lifetime" "${OUTDIR}/crv.hbond_lig_prot_lifetime.dat" "${OUTDIR}/05_hbond_lifetime.log" || true

        make_directional_hbond_summary "$i" "$OUTDIR" "${OUTDIR}/05_hbond_lifetime.log" || true

    else
        rep_failed=1
        maybe_abort_or_continue "Aborting after H-bond/lifetime failure."
    fi

    # =====================================================
    # 06) Ligand clustering
    #     Serial cpptraj + sieve reduces memory/MPI issues.
    # =====================================================

    cat > "${OUTDIR}/06_cluster.in" << EOF_IN
rms first ${LIG_MASK}
cluster hieragglo clusters ${NCLUSTERS} linkage average sieve ${CLUSTER_SIEVE} \
    summary ${OUTDIR}/cluster_summary.dat \
    out ${OUTDIR}/cluster.dat \
    repout ${OUTDIR}/cluster_rep repfmt pdb
run
quit
EOF_IN

    if run_cpptraj_step "$i" "06_cluster" "${OUTDIR}/06_cluster.in" "$CENTERED_TRAJ" "${OUTDIR}/06_cluster.log" "serial"; then
        require_output_file "$i" "06_cluster" "${OUTDIR}/cluster_summary.dat" "${OUTDIR}/06_cluster.log" || rep_failed=1
    else
        rep_failed=1
        maybe_abort_or_continue "Aborting after clustering failure."
    fi

    if [[ "$rep_failed" -eq 0 ]]; then
        echo "Replicate ${i} completed successfully."
        record_status "$i" "replicate_complete" "OK" "-" "all expected analyses completed"
    else
        echo "Replicate ${i} completed with warnings/errors. Check ${SUMMARY_FILE}."
        record_status "$i" "replicate_complete" "WARNING" "-" "some steps failed or outputs were missing"
        fail_global=1
    fi

    echo

done

echo "========================================================="
echo "Analysis loop finished."
echo "Summary: ${SUMMARY_FILE}"
echo "========================================================="

if grep -q $'\tFAILED\t' "$SUMMARY_FILE"; then
    echo "Some steps failed. Check the FAILED lines:"
    grep $'\tFAILED\t' "$SUMMARY_FILE" || true
    exit 2
fi

if grep -q $'\tWARNING\t' "$SUMMARY_FILE"; then
    echo "Some replicates finished with warnings. Check:"
    grep $'\tWARNING\t' "$SUMMARY_FILE" || true
    exit 1
fi

echo "All available replicates completed successfully."
exit 0
