#!/usr/bin/env bash

# ============================================================
# Mutation-effect analysis for AMBER/CPPTRAJ trajectories - v4
# Author: Lucas Palmeira / ChatGPT
#
# v4 changes requested by Lucas:
#   - The script recognizes trajectories already generated by the
#     previous replicate workflow and now PRIORITIZES them over raw trajectories:
#       replicate_analysis_1/step5_centered_1.nc
#       replicate_analysis_2/step5_centered_2.nc
#       replicate_analysis_3/step5_centered_3.nc
#   - It still keeps compatibility with raw trajectories in the main folder.
#
# Goal
# ----
# Run local, active-site/substrate, and allosteric/dynamic analyses
# to compare WT vs optimized GH32 enzymes in AMBER trajectories.
#
# You should execute this script separately in each system folder:
#   - endo optimized
#   - endo WT
#   - exo optimized
#   - exo WT
#
# Example:
#   SYSTEM_LABEL=endo_opt PROT_LAST_RES=623 LIG_MASK=':1CU,0CU' bash run_mutation_effect_analysis_v4.sh
#
# Notes
# -----
# 1. WT analyses use the equivalent residue positions for the mutated sites.
#    If residue numbering differs between WT and OPT, override MUT_RES manually.
# 2. Ligand RMSD and active-site RMSD are calculated after fitting the protein C-alpha atoms.
#    The keyword 'nofit' is used so that the ligand/catalytic-site RMSD reflects motion
#    relative to the protein frame, not an independent self-fit.
# 3. The script creates a README_ANALYSES.md inside the output folder explaining
#    each analysis, question, command class, and output file pattern.
# ============================================================

set -Eeuo pipefail

# -----------------------------
# User configuration
# -----------------------------
# Topology generated by CHARMM-GUI/AmberTools. Override with:
#   PARM=your_topology.parm7 bash run_mutation_effect_analysis_v4.sh
PARM="${PARM:-step3_input.parm7}"

# Which system is being analyzed. This controls the default residues.
# Accepted values with built-in defaults:
#   endo_opt, endo_wt, exo_opt, exo_wt
SYSTEM_LABEL="${SYSTEM_LABEL:-endo_opt}"

# Last protein residue number in the topology. This is used to define :1-PROT_LAST_RES.
PROT_LAST_RES="${PROT_LAST_RES:-623}"

# Ligand residue mask. Adjust if your inulin fragment has more residues, e.g. ':1CU,0CU,1GA'.
LIG_MASK="${LIG_MASK:-:1CU,0CU}"

# Replicates to analyze. Default is exactly your case: 1 2 3.
# Example to run only replicate 2:
#   REPLICATES='2' bash run_mutation_effect_analysis_v4.sh
REPLICATES=(${REPLICATES:-1 2 3})

# Optional manual overrides. If empty, defaults are set from SYSTEM_LABEL.
MUT_RES="${MUT_RES:-}"
MUT_LABELS="${MUT_LABELS:-}"
CAT_RES="${CAT_RES:-}"

# Analysis parameters
# MUT_WINDOW_RADIUS defines the local region around each mutated/equivalent residue.
# Example: radius 10 around residue 158 means residues 148-168.
MUT_WINDOW_RADIUS="${MUT_WINDOW_RADIUS:-10}"
CONTACT_CUTOFF="${CONTACT_CUTOFF:-4.0}"
LOCAL_CONTACT_CUTOFF="${LOCAL_CONTACT_CUTOFF:-4.5}"
HBOND_DIST="${HBOND_DIST:-3.5}"
HBOND_ANGLE="${HBOND_ANGLE:-120}"
NCLUSTERS="${NCLUSTERS:-3}"
CLUSTER_SIEVE="${CLUSTER_SIEVE:-10}"
PCA_VECS="${PCA_VECS:-5}"
DCCM_ENABLE="${DCCM_ENABLE:-yes}"
PCA_ENABLE="${PCA_ENABLE:-yes}"
PLOTS_ENABLE="${PLOTS_ENABLE:-yes}"
CLEAN_OUTPUT="${CLEAN_OUTPUT:-no}"
CONTINUE_ON_ERROR="${CONTINUE_ON_ERROR:-yes}"

# Output
OUTROOT="${OUTROOT:-mutation_effect_analysis_${SYSTEM_LABEL}}"

# -----------------------------
# Default residue definitions
# -----------------------------
case "${SYSTEM_LABEL}" in
    endo_opt)
        MUT_RES="${MUT_RES:-158 322}"
        MUT_LABELS="${MUT_LABELS:-G158S G322T}"
        CAT_RES="${CAT_RES:-40 176 252}"
        ;;
    endo_wt)
        # IMPORTANT: these are the equivalent mutation positions by default.
        # If the WT topology has shifted numbering, run with e.g. MUT_RES='178 342'.
        MUT_RES="${MUT_RES:-158 322}"
        MUT_LABELS="${MUT_LABELS:-G158_equiv G322_equiv}"
        CAT_RES="${CAT_RES:-60 196 272}"
        ;;
    exo_opt)
        MUT_RES="${MUT_RES:-106 297}"
        MUT_LABELS="${MUT_LABELS:-S106T A297G}"
        CAT_RES="${CAT_RES:-21 160 234}"
        ;;
    exo_wt)
        MUT_RES="${MUT_RES:-106 297}"
        MUT_LABELS="${MUT_LABELS:-S106_equiv A297_equiv}"
        CAT_RES="${CAT_RES:-21 160 234}"
        ;;
    *)
        if [[ -z "${MUT_RES}" || -z "${CAT_RES}" ]]; then
            echo "ERROR: unknown SYSTEM_LABEL='${SYSTEM_LABEL}'."
            echo "Either use one of: endo_opt, endo_wt, exo_opt, exo_wt"
            echo "or provide MUT_RES, MUT_LABELS, and CAT_RES manually."
            exit 1
        fi
        ;;
esac

# Convert to arrays
read -r -a MUT_ARRAY <<< "${MUT_RES}"
read -r -a LABEL_ARRAY <<< "${MUT_LABELS}"
read -r -a CAT_ARRAY <<< "${CAT_RES}"

if [[ "${#LABEL_ARRAY[@]}" -ne "${#MUT_ARRAY[@]}" ]]; then
    echo "WARNING: number of MUT_LABELS differs from MUT_RES. Using residue numbers as labels."
    LABEL_ARRAY=()
    for r in "${MUT_ARRAY[@]}"; do LABEL_ARRAY+=("res${r}"); done
fi

# -----------------------------
# Helper functions
# -----------------------------
timestamp() { date "+%Y-%m-%d %H:%M:%S"; }

fail_or_continue() {
    local msg="$1"
    echo "ERROR: ${msg}"
    if [[ "${CONTINUE_ON_ERROR}" == "yes" ]]; then
        echo "Continuing because CONTINUE_ON_ERROR=yes."
        return 0
    fi
    exit 1
}

sanitize_label() {
    echo "$1" | sed 's/[^A-Za-z0-9_.-]/_/g'
}

join_by_comma_residues() {
    local out=""
    local r
    for r in "$@"; do
        if [[ -z "${out}" ]]; then out="${r}"; else out="${out},${r}"; fi
    done
    echo ":${out}"
}

cat_mask() {
    local base
    base="$(join_by_comma_residues "${CAT_ARRAY[@]}")"
    echo "${base}"
}

cat_ca_mask() {
    echo "$(cat_mask)@CA"
}

cat_heavy_mask() {
    echo "$(cat_mask)&!@H="
}

window_range() {
    local res="$1"
    local start=$((res - MUT_WINDOW_RADIUS))
    local end=$((res + MUT_WINDOW_RADIUS))
    if (( start < 1 )); then start=1; fi
    if (( end > PROT_LAST_RES )); then end="${PROT_LAST_RES}"; fi
    echo "${start}-${end}"
}

all_mut_window_mask() {
    local parts=()
    local r
    for r in "${MUT_ARRAY[@]}"; do
        parts+=("$(window_range "${r}")")
    done
    local joined=""
    for p in "${parts[@]}"; do
        if [[ -z "${joined}" ]]; then joined="${p}"; else joined="${joined},${p}"; fi
    done
    echo ":${joined}"
}

find_trajectory() {
    local rep="$1"

    # Search for the trajectory of a given replicate.
    #
    # Priority in this v4 version:
    #   1) already centered trajectories from your previous workflow:
    #        replicate_analysis_1/step5_centered_1.nc
    #        replicate_analysis_2/step5_centered_2.nc
    #        replicate_analysis_3/step5_centered_3.nc
    #   2) raw production trajectories in the main AMBER directory.
    #
    # Why prioritize centered trajectories?
    #   You already generated them in the previous script. Using them avoids
    #   reading/re-imaging the huge raw step5_production_*.nc files unless
    #   the centered files are absent. The script will still write a standardized
    #   copy inside OUTROOT/01_centered/ so that each output folder remains
    #   self-contained and reproducible.

    local candidates=(
        # Centered trajectories produced by your existing replicate workflow
        "replicate_analysis_${rep}/step5_centered_${rep}.nc"

        # Raw trajectory names in the main AMBER directory, used only as fallback
        "step5_production_${rep}.nc"
        "step5_production.${rep}.nc"
        "step5_${rep}.nc"
    )

    # Some CHARMM-GUI/Amber workflows name replicate 1 simply step5_production.nc.
    # It is placed after the centered trajectory, so it is only a fallback.
    if [[ "${rep}" == "1" ]]; then
        candidates+=("step5_production.nc")
    fi

    local f
    for f in "${candidates[@]}"; do
        if [[ -f "${f}" ]]; then
            echo "${f}"
            return 0
        fi
    done

    return 1
}

run_cpptraj() {
    local input_file="$1"
    local traj_file="$2"
    local log_file="$3"
    echo "# Started: $(timestamp)" > "${log_file}"
    echo "# cpptraj -p ${PARM} -y ${traj_file} -i ${input_file}" >> "${log_file}"
    cpptraj -p "${PARM}" -y "${traj_file}" -i "${input_file}" >> "${log_file}" 2>&1
    local rc=$?
    echo "# Finished: $(timestamp)" >> "${log_file}"
    echo "# Exit code: ${rc}" >> "${log_file}"
    return "${rc}"
}

require_file_warn() {
    local f="$1"
    if [[ ! -s "${f}" ]]; then
        echo "WARNING: expected output missing or empty: ${f}"
        return 1
    fi
    return 0
}

# -----------------------------
# Basic checks
# -----------------------------
if [[ ! -f "${PARM}" ]]; then
    echo "ERROR: topology file not found: ${PARM}"
    exit 1
fi
if ! command -v cpptraj >/dev/null 2>&1; then
    echo "ERROR: cpptraj not found in PATH. Load AmberTools first."
    exit 1
fi

PROT_MASK=":1-${PROT_LAST_RES}"
CA_MASK="${PROT_MASK}@CA"
CAT_MASK="$(cat_mask)"
CAT_CA_MASK="$(cat_ca_mask)"
CAT_HEAVY_MASK="$(cat_heavy_mask)"
MUT_WINDOW_MASK="$(all_mut_window_mask)"
ACTIVE_CLUSTER_MASK="(${LIG_MASK}|${CAT_MASK}|${MUT_WINDOW_MASK})&!@H="
DYN_MASK="${CA_MASK}"

if [[ "${CLEAN_OUTPUT}" == "yes" && -d "${OUTROOT}" ]]; then
    rm -rf "${OUTROOT}"
fi

mkdir -p \
    "${OUTROOT}/00_logs" \
    "${OUTROOT}/01_centered" \
    "${OUTROOT}/02_local_mutation" \
    "${OUTROOT}/03_active_site_substrate" \
    "${OUTROOT}/04_allosteric_dynamic" \
    "${OUTROOT}/05_plots" \
    "${OUTROOT}/06_cpptraj_inputs"

SUMMARY="${OUTROOT}/analysis_status.tsv"
printf "Replicate\tAnalysis\tStatus\tLog\tNote\n" > "${SUMMARY}"

# -----------------------------
# README explaining the analyses
# -----------------------------
cat > "${OUTROOT}/README_ANALYSES.md" <<EOF_README
# Mutation-effect MD analysis: ${SYSTEM_LABEL}

Generated on: $(timestamp)

## System configuration

| Parameter | Value |
|---|---|
| Topology | \`${PARM}\` |
| Protein mask | \`${PROT_MASK}\` |
| Protein C-alpha mask | \`${CA_MASK}\` |
| Ligand mask | \`${LIG_MASK}\` |
| Mutated/equivalent residues | \`${MUT_RES}\` |
| Mutation labels | \`${MUT_LABELS}\` |
| Catalytic residues | \`${CAT_RES}\` |
| Mutation local window | ±${MUT_WINDOW_RADIUS} residues |
| Contact cutoff | ${CONTACT_CUTOFF} Å |
| Local contact cutoff | ${LOCAL_CONTACT_CUTOFF} Å |
| H-bond cutoff | distance ${HBOND_DIST} Å; angle ${HBOND_ANGLE}° |

## Trajectory discovery in v2

For each replicate, this script first searches for raw trajectories in the main folder and then searches for previously centered trajectories in your existing output folders. Therefore it recognizes paths such as:

```text
replicate_analysis_1/step5_centered_1.nc
replicate_analysis_2/step5_centered_2.nc
replicate_analysis_3/step5_centered_3.nc
```

If it uses one of these centered files, it still writes a standardized centered trajectory inside this new output folder so that the new analysis remains self-contained.

## What was already covered by your previous script

Your previous analysis already generated: centered trajectories, protein C-alpha RMSD, ligand RMSD, protein RMSF, radius of gyration, protein-ligand H-bond counts/occupancies/lifetimes, and ligand clustering.

This script extends that by focusing on mutation mechanisms.

## Analysis block 1: local effect of mutation

Biological question: did the mutation change flexibility, exposure, contacts, hydrogen bonds, or secondary structure around the mutated/equivalent residue?

For each mutated/equivalent residue and each replicate, this script calculates:

| Output pattern | Meaning | Question answered |
|---|---|---|
| \`local_rmsd_<label>_window_repX.dat\` | RMSD of ±${MUT_WINDOW_RADIUS}-residue window after protein C-alpha fit | Did the local region become more/less structurally stable? |
| \`local_rmsf_<label>_window_repX.dat\` | C-alpha RMSF by residue in the local window | Did the mutation reduce or increase local flexibility? |
| \`local_sasa_<label>_residue_repX.dat\` | SASA of the mutated/equivalent residue | Did the residue become more exposed or buried? |
| \`local_sasa_<label>_window_repX.dat\` | SASA of the mutation window | Did the local region become more exposed/buried? |
| \`local_secstruct_<label>_window_repX.gnu\` and \`*.sum.dat\` | DSSP secondary structure over time and average propensity | Did the local secondary structure change? |
| \`local_hbond_<label>_mutD_envA_*\` and \`local_hbond_<label>_envD_mutA_*\` | H-bonds involving the mutated/equivalent residue | Did the mutation create/disrupt local H-bond networks? |
| \`local_contacts_<label>_mut_lig_*\` | Contacts between mutated/equivalent residue and ligand | Does the mutated site contact the substrate? |
| \`local_contacts_<label>_window_lig_*\` | Contacts between local window and ligand | Did the local region become more engaged with substrate? |
| \`local_mindist_<label>_mut_lig_repX.dat\` | Minimum distance from mutated/equivalent residue to ligand | Does the residue approach the substrate? |
| \`local_mindist_<label>_mut_cat_repX.dat\` | Minimum distance from mutated/equivalent residue to catalytic residues | Does the residue approach the active-site machinery? |

CPPTRAJ commands used: \`rms ... nofit\`, \`atomicfluct ... byres\`, \`surf\`, \`secstruct\`, \`hbond\`, \`nativecontacts\`, and \`mindist\`.

## Analysis block 2: active-site and substrate effect

Biological question: did the mutation alter substrate stability or active-site geometry?

| Output pattern | Meaning | Question answered |
|---|---|---|
| \`active_rmsd_ligand_after_protein_fit_repX.dat\` | Ligand RMSD after protein C-alpha fit | Does the substrate remain more stably bound? |
| \`active_rmsd_catalytic_heavy_after_protein_fit_repX.dat\` | Heavy-atom RMSD of catalytic triad after protein fit | Is the catalytic geometry more stable? |
| \`active_rmsf_catalytic_ca_repX.dat\` | RMSF of catalytic residues | Are catalytic residues stabilized/destabilized? |
| \`active_mindist_cat_lig_all_repX.dat\` | Minimum distance catalytic triad ↔ ligand | Does the substrate remain close to catalytic residues? |
| \`active_mindist_cat<res>_lig_repX.dat\` | Minimum distance each catalytic residue ↔ ligand | Which catalytic residue remains closest to substrate? |
| \`active_hbond_ligD_catA_*\` and \`active_hbond_catD_ligA_*\` | Directional ligand-catalytic H-bonds | Are catalytic H-bonds more frequent/persistent? |
| \`active_contacts_lig_protein_*\` | Ligand-protein contacts | Does the substrate establish more contacts globally? |
| \`active_contacts_lig_catalytic_*\` | Ligand-catalytic contacts | Does the substrate maintain catalytic contacts? |
| \`active_contacts_lig_mutwindows_*\` | Ligand contacts with mutation windows | Do mutation neighborhoods contact the substrate? |

## Analysis block 3: allosteric/dynamic effect

Biological question: did mutations alter dynamic coupling, collective motions, or conformational populations?

| Output pattern | Meaning | Question answered |
|---|---|---|
| \`dynamic_dccm_ca_byres_repX.dat\` | Dynamic cross-correlation matrix using C-alpha atoms | Are mutation regions more/less correlated with active-site regions? |
| \`dynamic_atomiccorr_ca_byres_cut0p4_repX.dat\` | Strong residue-motion correlations | Which residue pairs show strong correlated/anti-correlated motion? |
| \`dynamic_pca_covar_ca_repX.dat\` | Coordinate covariance matrix | Basis for principal component analysis |
| \`dynamic_pca_evecs_repX.dat\` | PCA eigenvectors/eigenvalues | Which collective modes dominate motion? |
| \`dynamic_pca_eigenvalues_repX.dat\` | Fraction/cumulative contribution of modes | How concentrated is the motion in the first PCs? |
| \`dynamic_pca_projection_pc1_pc3_repX.dat\` | Projection onto PC1-PC3 | Did the system sample different conformational subspaces? |
| \`dynamic_cluster_active_region_summary_repX.dat\` | Clustering of ligand + catalytic residues + mutation windows | Did the complex occupy fewer/more conformational populations? |
| \`dynamic_cluster_active_region_repX.c*.pdb\` | Representative structures | Which conformations represent dominant states? |

## Important comparison logic

Run this script separately for WT and OPT. Then compare equivalent outputs across conditions and triplicates. Stronger conclusions require trends consistent in at least two or three replicates.

For endo WT, your catalytic residues were set to D60/D196/E272. For endo OPT, D40/D176/E252. For exo WT and exo OPT, D21/D160/E234.

For WT local mutation analysis, this script uses the equivalent mutation positions by default. If the WT topology has shifted residue numbering, rerun with explicit \`MUT_RES\`.

EOF_README

# -----------------------------
# Generate plotting helper script
# -----------------------------
cat > "${OUTROOT}/plot_mutation_effects.py" <<'PY'
#!/usr/bin/env python3
"""Generic plotter for run_mutation_effect_analysis.sh outputs."""
from __future__ import annotations

import os
import re
import sys
from pathlib import Path

try:
    import numpy as np
    import matplotlib.pyplot as plt
except Exception as exc:  # pragma: no cover
    print(f"Plotting disabled: could not import numpy/matplotlib: {exc}")
    sys.exit(0)

ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path.cwd()
PLOTS = ROOT / "05_plots"
PLOTS.mkdir(parents=True, exist_ok=True)


def read_numeric_table(path: Path):
    rows = []
    with path.open(errors="ignore") as handle:
        for line in handle:
            s = line.strip()
            if not s or s.startswith("#") or s.startswith("@"):
                continue
            parts = re.split(r"\s+", s)
            nums = []
            ok = True
            for p in parts:
                try:
                    nums.append(float(p))
                except ValueError:
                    ok = False
                    break
            if ok and len(nums) >= 2:
                rows.append(nums)
    if not rows:
        return None
    ncols = min(len(r) for r in rows)
    return np.array([r[:ncols] for r in rows], dtype=float)


def safe_name(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    return re.sub(r"[^A-Za-z0-9_.-]+", "_", rel)


def plot_xy(path: Path, arr: np.ndarray, ylabel: str):
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(arr[:, 0], arr[:, 1], linewidth=1.2)
    ax.set_xlabel("Frame")
    ax.set_ylabel(ylabel)
    ax.set_title(path.stem)
    fig.tight_layout()
    fig.savefig(PLOTS / f"{safe_name(path)}.png", dpi=300)
    plt.close(fig)


def plot_rmsf(path: Path, arr: np.ndarray):
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(arr[:, 0], arr[:, 1], marker="o", markersize=2, linewidth=1.0)
    ax.set_xlabel("Residue")
    ax.set_ylabel("RMSF (Å)")
    ax.set_title(path.stem)
    fig.tight_layout()
    fig.savefig(PLOTS / f"{safe_name(path)}.png", dpi=300)
    plt.close(fig)


def plot_heatmap(path: Path, arr: np.ndarray, title: str):
    if arr.ndim != 2 or arr.shape[0] < 2 or arr.shape[1] < 2:
        return
    fig, ax = plt.subplots(figsize=(6, 5))
    im = ax.imshow(arr, origin="lower", aspect="auto", vmin=-1, vmax=1, cmap="coolwarm")
    ax.set_title(title)
    ax.set_xlabel("Residue index")
    ax.set_ylabel("Residue index")
    fig.colorbar(im, ax=ax, label="Correlation")
    fig.tight_layout()
    fig.savefig(PLOTS / f"{safe_name(path)}.png", dpi=300)
    plt.close(fig)


def plot_pca_projection(path: Path, arr: np.ndarray):
    # Common cpptraj projection format: frame PC1 PC2 PC3 ...
    if arr.shape[1] < 3:
        return
    fig, ax = plt.subplots(figsize=(5, 5))
    ax.scatter(arr[:, 1], arr[:, 2], s=8, alpha=0.7)
    ax.set_xlabel("PC1 projection")
    ax.set_ylabel("PC2 projection")
    ax.set_title(path.stem)
    fig.tight_layout()
    fig.savefig(PLOTS / f"{safe_name(path)}.png", dpi=300)
    plt.close(fig)


def plot_contact_resout(path: Path, arr: np.ndarray):
    # nativecontacts resout usually: Res1 Res2 TotalFrac Contacts
    if arr.shape[1] < 3:
        return
    # Top 20 by TotalFrac
    idx = np.argsort(arr[:, 2])[-20:]
    sub = arr[idx]
    labels = [f"{int(r1)}-{int(r2)}" for r1, r2 in sub[:, :2]]
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.barh(np.arange(len(labels)), sub[:, 2])
    ax.set_yticks(np.arange(len(labels)))
    ax.set_yticklabels(labels, fontsize=7)
    ax.set_xlabel("Total contact fraction")
    ax.set_title(path.stem)
    fig.tight_layout()
    fig.savefig(PLOTS / f"{safe_name(path)}.png", dpi=300)
    plt.close(fig)


for path in ROOT.rglob("*.dat"):
    if "05_plots" in path.parts:
        continue
    arr = read_numeric_table(path)
    if arr is None:
        continue
    name = path.name.lower()
    if "dccm" in name and arr.shape[0] > 2 and arr.shape[1] > 2:
        plot_heatmap(path, arr, "DCCM C-alpha by residue")
    elif "pca_projection" in name:
        plot_pca_projection(path, arr)
    elif "resout" in name or "contacts" in name and arr.shape[1] >= 3:
        # Only try bar plots for residue-pair summary-like files.
        if arr.shape[1] >= 3 and arr.shape[0] <= 5000:
            plot_contact_resout(path, arr)
    elif "rmsf" in name:
        plot_rmsf(path, arr)
    elif "rmsd" in name:
        plot_xy(path, arr, "RMSD (Å)")
    elif "sasa" in name or "surf" in name:
        plot_xy(path, arr, "SASA (Å²)")
    elif "mindist" in name or "distance" in name or "dist" in name:
        plot_xy(path, arr, "Distance (Å)")
    elif "hbond" in name and arr.shape[1] >= 2:
        plot_xy(path, arr, "H-bond count")

print(f"Plots written to: {PLOTS}")
PY

# -----------------------------
# Start log
# -----------------------------
echo "============================================================"
echo "Mutation-effect analysis"
echo "============================================================"
echo "System label:       ${SYSTEM_LABEL}"
echo "Topology:           ${PARM}"
echo "Protein mask:       ${PROT_MASK}"
echo "Ligand mask:        ${LIG_MASK}"
echo "Mut/equiv residues: ${MUT_RES}"
echo "Mutation labels:    ${MUT_LABELS}"
echo "Catalytic residues: ${CAT_RES}"
echo "Output folder:      ${OUTROOT}"
echo "Replicates:         ${REPLICATES[*]}"
echo "Trajectory search:  replicate_analysis_*/step5_centered_*.nc first; raw trajectories as fallback"
echo "============================================================"

# -----------------------------
# Main replicate loop
# -----------------------------
for rep in "${REPLICATES[@]}"; do
    echo
    echo "-----------------------------"
    echo "Replicate ${rep}"
    echo "-----------------------------"

    TRAJ=""
    if TRAJ="$(find_trajectory "${rep}")"; then
        echo "Trajectory: ${TRAJ}"
    else
        echo "WARNING: no trajectory found for replicate ${rep}. Skipping."
        printf "%s\ttrajectory_check\tSKIPPED\t-\ttrajectory not found\n" "${rep}" >> "${SUMMARY}"
        continue
    fi

    CENTERED="${OUTROOT}/01_centered/rep${rep}_centered.nc"

    # 01) Center/imaging
    CENTER_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_01_center.in"
    cat > "${CENTER_IN}" <<EOF_CPP
# Center and image trajectory
# Question: prepare a stable reference frame for all analyses.
autoimage anchor ${PROT_MASK}
center ${PROT_MASK} mass origin
image origin center
rms ProteinFit first ${CA_MASK} out ${OUTROOT}/01_centered/rep${rep}_protein_fit_rmsd_during_centering.dat
trajout ${CENTERED} netcdf
run
quit
EOF_CPP

    if run_cpptraj "${CENTER_IN}" "${TRAJ}" "${OUTROOT}/00_logs/rep${rep}_01_center.log"; then
        printf "%s\t01_center\tOK\t%s\tcentered trajectory generated\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_01_center.log" >> "${SUMMARY}"
    else
        printf "%s\t01_center\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_01_center.log" >> "${SUMMARY}"
        fail_or_continue "centering failed for replicate ${rep}"
        continue
    fi

    if [[ ! -s "${CENTERED}" ]]; then
        printf "%s\t01_center\tFAILED\t%s\tcentered trajectory missing\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_01_center.log" >> "${SUMMARY}"
        fail_or_continue "centered trajectory missing for replicate ${rep}"
        continue
    fi

    # 02) Local mutation analyses
    LOCAL_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_02_local_mutation.in"
    {
        echo "# Local mutation/equivalent-position analysis"
        echo "strip :WAT,Na+,Cl-,K+"
        echo "rms ProteinFit first ${CA_MASK}"
        echo
        for idx in "${!MUT_ARRAY[@]}"; do
            res="${MUT_ARRAY[$idx]}"
            label="$(sanitize_label "${LABEL_ARRAY[$idx]}")"
            range="$(window_range "${res}")"
            echo "# ------------------------------------------------------------"
            echo "# ${label}: residue ${res}; local window ${range}"
            echo "# ------------------------------------------------------------"
            echo "rms LocalRMSD_${label} first :${range}@CA nofit out ${OUTROOT}/02_local_mutation/local_rmsd_${label}_window_rep${rep}.dat"
            echo "atomicfluct out ${OUTROOT}/02_local_mutation/local_rmsf_${label}_window_rep${rep}.dat :${range}@CA byres"
            echo "surf SASA_${label}_res :${res} out ${OUTROOT}/02_local_mutation/local_sasa_${label}_residue_rep${rep}.dat solutemask ${PROT_MASK},${LIG_MASK}"
            echo "surf SASA_${label}_win :${range} out ${OUTROOT}/02_local_mutation/local_sasa_${label}_window_rep${rep}.dat solutemask ${PROT_MASK},${LIG_MASK}"
            echo "secstruct SS_${label} :${range} out ${OUTROOT}/02_local_mutation/local_secstruct_${label}_window_rep${rep}.gnu sumout ${OUTROOT}/02_local_mutation/local_secstruct_${label}_window_sum_rep${rep}.dat assignout ${OUTROOT}/02_local_mutation/local_secstruct_${label}_window_assign_rep${rep}.dat totalout ${OUTROOT}/02_local_mutation/local_secstruct_${label}_window_total_rep${rep}.dat"
            echo "hbond HB_${label}_mutD_envA out ${OUTROOT}/02_local_mutation/local_hbond_${label}_mutD_envA_counts_rep${rep}.dat avgout ${OUTROOT}/02_local_mutation/local_hbond_${label}_mutD_envA_avg_rep${rep}.dat donormask :${res} acceptormask (:${range}|${LIG_MASK}) image dist ${HBOND_DIST} angle ${HBOND_ANGLE} printatomnum"
            echo "hbond HB_${label}_envD_mutA out ${OUTROOT}/02_local_mutation/local_hbond_${label}_envD_mutA_counts_rep${rep}.dat avgout ${OUTROOT}/02_local_mutation/local_hbond_${label}_envD_mutA_avg_rep${rep}.dat donormask (:${range}|${LIG_MASK}) acceptormask :${res} image dist ${HBOND_DIST} angle ${HBOND_ANGLE} printatomnum"
            echo "nativecontacts name NC_${label}_mut_lig :${res}&!@H= ${LIG_MASK}&!@H= byresidue distance ${CONTACT_CUTOFF} out ${OUTROOT}/02_local_mutation/local_contacts_${label}_mut_lig_count_rep${rep}.dat resout ${OUTROOT}/02_local_mutation/local_contacts_${label}_mut_lig_resout_rep${rep}.dat writecontacts ${OUTROOT}/02_local_mutation/local_contacts_${label}_mut_lig_pairs_rep${rep}.dat series seriesout ${OUTROOT}/02_local_mutation/local_contacts_${label}_mut_lig_series_rep${rep}.dat savenonnative"
            echo "nativecontacts name NC_${label}_win_lig :${range}&!@H= ${LIG_MASK}&!@H= byresidue distance ${LOCAL_CONTACT_CUTOFF} out ${OUTROOT}/02_local_mutation/local_contacts_${label}_window_lig_count_rep${rep}.dat resout ${OUTROOT}/02_local_mutation/local_contacts_${label}_window_lig_resout_rep${rep}.dat writecontacts ${OUTROOT}/02_local_mutation/local_contacts_${label}_window_lig_pairs_rep${rep}.dat series seriesout ${OUTROOT}/02_local_mutation/local_contacts_${label}_window_lig_series_rep${rep}.dat savenonnative"
            echo "mindist mask1 :${res}&!@H= mask2 ${LIG_MASK}&!@H= out ${OUTROOT}/02_local_mutation/local_mindist_${label}_mut_lig_rep${rep}.dat"
            echo "mindist mask1 :${res}&!@H= mask2 ${CAT_HEAVY_MASK} out ${OUTROOT}/02_local_mutation/local_mindist_${label}_mut_cat_rep${rep}.dat"
            echo
        done
        echo "run"
        echo "quit"
    } > "${LOCAL_IN}"

    if run_cpptraj "${LOCAL_IN}" "${CENTERED}" "${OUTROOT}/00_logs/rep${rep}_02_local_mutation.log"; then
        printf "%s\t02_local_mutation\tOK\t%s\tlocal mutation analyses completed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_02_local_mutation.log" >> "${SUMMARY}"
    else
        printf "%s\t02_local_mutation\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_02_local_mutation.log" >> "${SUMMARY}"
        fail_or_continue "local mutation analysis failed for replicate ${rep}"
    fi

    # 03) Active-site and substrate analyses
    ACTIVE_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_03_active_site_substrate.in"
    {
        echo "# Active-site and substrate analysis"
        echo "strip :WAT,Na+,Cl-,K+"
        echo "rms ProteinFit first ${CA_MASK}"
        echo "rms LigandAfterProteinFit first ${LIG_MASK} nofit out ${OUTROOT}/03_active_site_substrate/active_rmsd_ligand_after_protein_fit_rep${rep}.dat"
        echo "rms CatalyticHeavyAfterProteinFit first ${CAT_HEAVY_MASK} nofit out ${OUTROOT}/03_active_site_substrate/active_rmsd_catalytic_heavy_after_protein_fit_rep${rep}.dat"
        echo "atomicfluct out ${OUTROOT}/03_active_site_substrate/active_rmsf_catalytic_ca_rep${rep}.dat ${CAT_CA_MASK} byres"
        echo "mindist mask1 ${CAT_HEAVY_MASK} mask2 ${LIG_MASK}&!@H= out ${OUTROOT}/03_active_site_substrate/active_mindist_cat_lig_all_rep${rep}.dat"
        for catres in "${CAT_ARRAY[@]}"; do
            echo "mindist mask1 :${catres}&!@H= mask2 ${LIG_MASK}&!@H= out ${OUTROOT}/03_active_site_substrate/active_mindist_cat${catres}_lig_rep${rep}.dat"
        done
        echo "hbond HB_ligD_catA out ${OUTROOT}/03_active_site_substrate/active_hbond_ligD_catA_counts_rep${rep}.dat avgout ${OUTROOT}/03_active_site_substrate/active_hbond_ligD_catA_avg_rep${rep}.dat donormask ${LIG_MASK} acceptormask ${CAT_MASK} image dist ${HBOND_DIST} angle ${HBOND_ANGLE} printatomnum"
        echo "hbond HB_catD_ligA out ${OUTROOT}/03_active_site_substrate/active_hbond_catD_ligA_counts_rep${rep}.dat avgout ${OUTROOT}/03_active_site_substrate/active_hbond_catD_ligA_avg_rep${rep}.dat donormask ${CAT_MASK} acceptormask ${LIG_MASK} image dist ${HBOND_DIST} angle ${HBOND_ANGLE} printatomnum"
        echo "nativecontacts name NC_lig_protein ${LIG_MASK}&!@H= ${PROT_MASK}&!@H= byresidue distance ${CONTACT_CUTOFF} out ${OUTROOT}/03_active_site_substrate/active_contacts_lig_protein_count_rep${rep}.dat resout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_protein_resout_rep${rep}.dat writecontacts ${OUTROOT}/03_active_site_substrate/active_contacts_lig_protein_pairs_rep${rep}.dat series seriesout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_protein_series_rep${rep}.dat savenonnative"
        echo "nativecontacts name NC_lig_cat ${LIG_MASK}&!@H= ${CAT_HEAVY_MASK} byresidue distance ${CONTACT_CUTOFF} out ${OUTROOT}/03_active_site_substrate/active_contacts_lig_catalytic_count_rep${rep}.dat resout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_catalytic_resout_rep${rep}.dat writecontacts ${OUTROOT}/03_active_site_substrate/active_contacts_lig_catalytic_pairs_rep${rep}.dat series seriesout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_catalytic_series_rep${rep}.dat savenonnative"
        echo "nativecontacts name NC_lig_mutwins ${LIG_MASK}&!@H= ${MUT_WINDOW_MASK}&!@H= byresidue distance ${LOCAL_CONTACT_CUTOFF} out ${OUTROOT}/03_active_site_substrate/active_contacts_lig_mutwindows_count_rep${rep}.dat resout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_mutwindows_resout_rep${rep}.dat writecontacts ${OUTROOT}/03_active_site_substrate/active_contacts_lig_mutwindows_pairs_rep${rep}.dat series seriesout ${OUTROOT}/03_active_site_substrate/active_contacts_lig_mutwindows_series_rep${rep}.dat savenonnative"
        echo "run"
        echo "quit"
    } > "${ACTIVE_IN}"

    if run_cpptraj "${ACTIVE_IN}" "${CENTERED}" "${OUTROOT}/00_logs/rep${rep}_03_active_site_substrate.log"; then
        printf "%s\t03_active_site_substrate\tOK\t%s\tactive-site/substrate analyses completed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_03_active_site_substrate.log" >> "${SUMMARY}"
    else
        printf "%s\t03_active_site_substrate\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_03_active_site_substrate.log" >> "${SUMMARY}"
        fail_or_continue "active-site/substrate analysis failed for replicate ${rep}"
    fi

    # 04A) DCCM / residue correlation
    if [[ "${DCCM_ENABLE}" == "yes" ]]; then
        DCCM_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_04a_dccm.in"
        cat > "${DCCM_IN}" <<EOF_CPP
# Dynamic cross-correlation analysis
# Question: are mutation windows dynamically coupled to catalytic/active-site residues?
strip :WAT,Na+,Cl-,K+
rms ProteinFit first ${CA_MASK}
matrix correl name DCCM_CA ${CA_MASK} out ${OUTROOT}/04_allosteric_dynamic/dynamic_dccm_ca_byres_rep${rep}.dat byres
atomiccorr ${CA_MASK} out ${OUTROOT}/04_allosteric_dynamic/dynamic_atomiccorr_ca_byres_cut0p4_rep${rep}.dat cut 0.4 byres
run
quit
EOF_CPP
        if run_cpptraj "${DCCM_IN}" "${CENTERED}" "${OUTROOT}/00_logs/rep${rep}_04a_dccm.log"; then
            printf "%s\t04a_dccm\tOK\t%s\tDCCM/correlation completed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04a_dccm.log" >> "${SUMMARY}"
        else
            printf "%s\t04a_dccm\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04a_dccm.log" >> "${SUMMARY}"
            fail_or_continue "DCCM/correlation analysis failed for replicate ${rep}"
        fi
    fi

    # 04B) PCA
    if [[ "${PCA_ENABLE}" == "yes" ]]; then
        PCA_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_04b_pca.in"
        cat > "${PCA_IN}" <<EOF_CPP
# PCA / essential dynamics using protein C-alpha atoms
# Question: did the mutation alter dominant collective modes?
strip :WAT,Na+,Cl-,K+
rms ProteinFit first ${CA_MASK}
matrix covar name COVAR_CA ${DYN_MASK} out ${OUTROOT}/04_allosteric_dynamic/dynamic_pca_covar_ca_rep${rep}.dat
run
runanalysis diagmatrix COVAR_CA out ${OUTROOT}/04_allosteric_dynamic/dynamic_pca_evecs_rep${rep}.dat vecs ${PCA_VECS} name EIG_CA
runanalysis modes name EIG_CA eigenval out ${OUTROOT}/04_allosteric_dynamic/dynamic_pca_eigenvalues_rep${rep}.dat
projection PC evecs EIG_CA out ${OUTROOT}/04_allosteric_dynamic/dynamic_pca_projection_pc1_pc3_rep${rep}.dat beg 1 end 3 ${DYN_MASK}
run
quit
EOF_CPP
        if run_cpptraj "${PCA_IN}" "${CENTERED}" "${OUTROOT}/00_logs/rep${rep}_04b_pca.log"; then
            printf "%s\t04b_pca\tOK\t%s\tPCA completed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04b_pca.log" >> "${SUMMARY}"
        else
            printf "%s\t04b_pca\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04b_pca.log" >> "${SUMMARY}"
            fail_or_continue "PCA analysis failed for replicate ${rep}"
        fi
    fi

    # 04C) Clustering of active region
    # Important: CPPTRAJ uses "averagelinkage" as one keyword, not "linkage average".
    CLUSTER_IN="${OUTROOT}/06_cpptraj_inputs/rep${rep}_04c_active_region_cluster.in"
    cat > "${CLUSTER_IN}" <<EOF_CPP
# Active-region clustering
# Region: ligand + catalytic residues + mutation windows
# Question: did the system concentrate into fewer/more conformational populations?
strip :WAT,Na+,Cl-,K+
rms ProteinFit first ${CA_MASK}
cluster C_ACTIVE hieragglo clusters ${NCLUSTERS} averagelinkage sieve ${CLUSTER_SIEVE} random \
    rms ${ACTIVE_CLUSTER_MASK} \
    summary ${OUTROOT}/04_allosteric_dynamic/dynamic_cluster_active_region_summary_rep${rep}.dat \
    out ${OUTROOT}/04_allosteric_dynamic/dynamic_cluster_active_region_cnumvtime_rep${rep}.dat \
    cpopvtime ${OUTROOT}/04_allosteric_dynamic/dynamic_cluster_active_region_cpopvtime_rep${rep}.dat normframe \
    repout ${OUTROOT}/04_allosteric_dynamic/dynamic_cluster_active_region_rep${rep} repfmt pdb \
    avgout ${OUTROOT}/04_allosteric_dynamic/dynamic_cluster_active_region_avg${rep} avgfmt pdb
run
quit
EOF_CPP

    if run_cpptraj "${CLUSTER_IN}" "${CENTERED}" "${OUTROOT}/00_logs/rep${rep}_04c_active_region_cluster.log"; then
        printf "%s\t04c_active_region_cluster\tOK\t%s\tactive-region clustering completed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04c_active_region_cluster.log" >> "${SUMMARY}"
    else
        printf "%s\t04c_active_region_cluster\tFAILED\t%s\tcpptraj failed\n" "${rep}" "${OUTROOT}/00_logs/rep${rep}_04c_active_region_cluster.log" >> "${SUMMARY}"
        fail_or_continue "active-region clustering failed for replicate ${rep}"
    fi

done

# -----------------------------
# Plot all numeric outputs
# -----------------------------
if [[ "${PLOTS_ENABLE}" == "yes" ]]; then
    if command -v python3 >/dev/null 2>&1; then
        echo
        echo "Generating plots with Python..."
        if python3 "${OUTROOT}/plot_mutation_effects.py" "${OUTROOT}" > "${OUTROOT}/00_logs/plotting.log" 2>&1; then
            printf "all\tplotting\tOK\t%s\tPNG plots generated\n" "${OUTROOT}/00_logs/plotting.log" >> "${SUMMARY}"
        else
            printf "all\tplotting\tWARNING\t%s\tplotting script failed or dependencies missing\n" "${OUTROOT}/00_logs/plotting.log" >> "${SUMMARY}"
            echo "WARNING: plotting failed. Check ${OUTROOT}/00_logs/plotting.log"
        fi
    else
        printf "all\tplotting\tSKIPPED\t-\tpython3 not found\n" >> "${SUMMARY}"
        echo "WARNING: python3 not found; skipping plots."
    fi
fi

echo
echo "============================================================"
echo "Finished mutation-effect analysis"
echo "Output folder: ${OUTROOT}"
echo "Summary:       ${SUMMARY}"
echo "README:        ${OUTROOT}/README_ANALYSES.md"
echo "Plots:         ${OUTROOT}/05_plots"
echo "============================================================"

if grep -q $'\tFAILED\t' "${SUMMARY}"; then
    echo "Some analyses failed. Check:"
    grep $'\tFAILED\t' "${SUMMARY}" || true
    exit 2
fi

if grep -q $'\tWARNING\t' "${SUMMARY}"; then
    echo "Some analyses finished with warnings. Check:"
    grep $'\tWARNING\t' "${SUMMARY}" || true
    exit 1
fi

exit 0
